### ISSUE TITLE
Can this library handle calling Rust code from managed code as well?

### ISSUE THREAD

**Issue by JasonMiesionczek** [OpenByteDev/netcorehost#21]

**Comment by OpenByteDev** [comment]
You can call exported Rust functions from C# using DllImport or by passing the raw Rust function pointers via arguments to managed methods (this can be seen in the passing-parameters examples)

**Comment by JasonMiesionczek** [comment]
can the dllimport method be used in the same crate that is hosting the .net
runtime?

**Comment by OpenByteDev** [comment]
If the code that hosts the runtime resides inside a `.dll` then `[DllImport]` will work out of the box. Otherwise you will need a seperate `.dll` or manually load the functions using something like [`NativeLibrary`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=net-6.0).
